theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
scrolloff = 10
shell = ["bash", "-c"]
auto-pairs = true

[editor.statusline]
left = ["mode", "file-name"]
right = ["diagnostics", "position", "file-type"]
separator = "|"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false
ignore = false
